apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: three-tier-ingress-host
  namespace: 3tier
spec:
  rules:
    - host: nginx.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-svc
                port:
                  number: 81
    - host: python.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-svc
                port:
                  number: 5001
    - host: mysql.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mysql-svc
                port:
                  number: 3307
