apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: three-tier-ingress-path
  namespace: 3tier
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: nginx-svc
            port:
              number: 81
      - path: /python
        pathType: Prefix
        backend:
          service:
            name: python-svc
            port:
              number: 5001
      - path: /mysql
        pathType: Prefix
        backend:
          service:
            name: mysql-svc
            port:
              number: 3307

